<a href="https://colab.research.google.com/github/lari-guimaraes/Estudos_machine_learning/blob/main/Medidas_de_posi%C3%A7%C3%A3o_e_dispers%C3%A3o.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import statistics
from scipy import stats
import math

## Base de dados

In [46]:
dados = np.array([150,151,152,152,153,154,155,155,155,155,156,156,156,
                  157,158,158,160,160,160,160,160,161,161,161,161,162,
                  163,163,164,164,164,165,166,167,168,168,169,170,172,
                  173])

## Média Aritmética simples

In [3]:
dados.sum() / len(dados)

160.375

In [4]:
dados.mean()

160.375

In [5]:
statistics.mean(dados)

160

## Moda

In [6]:
statistics.mode(dados)

160

In [7]:
stats.mode(dados)

ModeResult(mode=array([160]), count=array([5]))

## Mediana

In [8]:
np.median(dados)

160.0

In [9]:
statistics.median(dados)

160.0

## Média aritmética ponderada

In [10]:
notas = np.array([9,8,7,3])
pesos = np.array([1,2,3,4])

In [11]:
media_ponderada = (notas*pesos).sum() / pesos.sum()
media_ponderada

5.8

In [12]:
np.average(notas, weights=pesos)

5.8

## Média aritmética, moda e mediana com distribuição de frequência (dados agrupados)

In [13]:
dados = {'inferior':[150,154,158,162,166,170],
         'superior':[154,158,162,166,170,174],
         'fi':[5,9,11,7,5,3]}

In [14]:
import pandas as pd

dataset = pd.DataFrame(dados)
dataset

inferior  superior  fi
0       150       154   5
1       154       158   9
2       158       162  11
3       162       166   7
4       166       170   5
5       170       174   3

In [15]:
dataset['xi'] = (dataset['superior'] + dataset['inferior'])/2
dataset

inferior  superior  fi     xi
0       150       154   5  152.0
1       154       158   9  156.0
2       158       162  11  160.0
3       162       166   7  164.0
4       166       170   5  168.0
5       170       174   3  172.0

In [16]:
dataset['fi.xi'] = dataset['fi'] * dataset['xi']
dataset

inferior  superior  fi     xi   fi.xi
0       150       154   5  152.0   760.0
1       154       158   9  156.0  1404.0
2       158       162  11  160.0  1760.0
3       162       166   7  164.0  1148.0
4       166       170   5  168.0   840.0
5       170       174   3  172.0   516.0

In [17]:
dataset['Fi'] = 0
dataset

inferior  superior  fi     xi   fi.xi  Fi
0       150       154   5  152.0   760.0   0
1       154       158   9  156.0  1404.0   0
2       158       162  11  160.0  1760.0   0
3       162       166   7  164.0  1148.0   0
4       166       170   5  168.0   840.0   0
5       170       174   3  172.0   516.0   0

In [18]:
frequencia_acumulada = []
somatorio = 0
for linha in dataset.iterrows():
  #print(linha)
  #print(linha[1][2])
  somatorio += linha[1][2]
  frequencia_acumulada.append(somatorio)

In [19]:
frequencia_acumulada

[5.0, 14.0, 25.0, 32.0, 37.0, 40.0]

In [20]:
dataset['Fi'] = frequencia_acumulada
dataset

inferior  superior  fi     xi   fi.xi    Fi
0       150       154   5  152.0   760.0   5.0
1       154       158   9  156.0  1404.0  14.0
2       158       162  11  160.0  1760.0  25.0
3       162       166   7  164.0  1148.0  32.0
4       166       170   5  168.0   840.0  37.0
5       170       174   3  172.0   516.0  40.0

### Média

In [21]:
dataset['fi'].sum(), dataset['fi.xi'].sum()

(40, 6428.0)

In [22]:
dataset['fi.xi'].sum()/dataset['fi'].sum()

160.7

### Moda

In [23]:
dataset['fi'].max()

11

In [24]:
dataset[dataset['fi'] == dataset['fi'].max()]

inferior  superior  fi     xi   fi.xi    Fi
2       158       162  11  160.0  1760.0  25.0

In [25]:
dataset[dataset['fi'] == dataset['fi'].max()]['xi'].values[0]

160.0

## Mediana

In [26]:
dataset

inferior  superior  fi     xi   fi.xi    Fi
0       150       154   5  152.0   760.0   5.0
1       154       158   9  156.0  1404.0  14.0
2       158       162  11  160.0  1760.0  25.0
3       162       166   7  164.0  1148.0  32.0
4       166       170   5  168.0   840.0  37.0
5       170       174   3  172.0   516.0  40.0

In [27]:
fi_2 = dataset['fi'].sum() / 2
fi_2

20.0

In [28]:
limite_inferior, frequencia_classe, id_frequencia_anterior = 0,0,0
for linha in dataset.iterrows():
  #print(linha)
  limite_inferior = linha[1][0]
  frequencia_classe = linha[1][2]
  id_frequencia_anterior = linha[0]
  if linha[1][5] >= fi_2:
    id_frequencia_anterior -= 1
    break


In [29]:
limite_inferior, frequencia_classe, id_frequencia_anterior

(158.0, 11.0, 1)

In [30]:
Fi_anterior = dataset.iloc[[id_frequencia_anterior]]['Fi'].values[0]
Fi_anterior

14.0

In [31]:
mediana = limite_inferior + ((fi_2 - Fi_anterior) * 4)/frequencia_classe
mediana

160.1818181818182

In [32]:
def get_estatisticas(dataframe):
  media = dataset['fi.xi'].sum() / dataset['fi'].sum()
  moda = dataset[dataset['fi'] == dataset['fi'].max()]['xi'].values[0]

  fi_2 = dataset['fi'].sum() / 2
  limite_inferior, frequencia_classe, id_frequencia_anterior = 0,0,0
  for linha in dataset.iterrows():
    #print(linha)
    limite_inferior = linha[1][0]
    frequencia_classe = linha[1][2]
    id_frequencia_anterior = linha[0]
    if linha[1][5] >= fi_2:
      id_frequencia_anterior -= 1
      break
  Fi_anterior = dataset.iloc[[id_frequencia_anterior]]['Fi'].values[0]
  mediana = limite_inferior + ((fi_2 - Fi_anterior) * 4)/frequencia_classe

  return media, moda, mediana

In [33]:
get_estatisticas(dataset)

(160.7, 160.0, 160.1818181818182)

## Quartis

In [34]:
dados_impar = [150, 151, 152, 152, 153, 154, 155, 155, 155]

### Cálculo manual

In [35]:
np.median(dados_impar)

153.0

In [36]:
posicao_mediana = math.floor(len(dados_impar) / 2)
posicao_mediana

4

In [37]:
esquerda = dados_impar[0:posicao_mediana]
esquerda

[150, 151, 152, 152]

In [38]:
np.median(esquerda)

151.5

In [39]:
direita = dados_impar[posicao_mediana + 1:]
direita

[154, 155, 155, 155]

In [40]:
np.median(direita)

155.0

### Bibliotecas

In [41]:
# numpy

np.quantile(dados_impar, 0.5)

153.0

In [42]:
np.quantile(dados_impar, 0.75)

155.0

## Quartis com dados agrupados

In [43]:
def get_quartil(dataframe, q1 = True):
  if q1 == True:
    fi_4 = dataset['fi.xi'].sum() / 4
  else: 
    fi_4 = (3 * dataset['fi.xi'].sum()) / 4

  limite_inferior, frequencia_classe, id_frequencia_anterior = 0,0,0
  for linha in dataset.iterrows():
    #print(linha)
    limite_inferior = linha[1][0]
    frequencia_classe = linha[1][2]
    id_frequencia_anterior = linha[0]
    if linha[1][5] >= fi_4:
      id_frequencia_anterior -= 1
      break
  Fi_anterior = dataset.iloc[[id_frequencia_anterior]]['Fi'].values[0]
  q = limite_inferior + ((fi_4 - Fi_anterior) * 4)/frequencia_classe
  return q

In [44]:
get_quartil(dados), get_quartil(dados, q1 = False)

(2259.3333333333335, 6544.666666666667)

## Percentis

In [47]:
np.median(dados)

160.0

In [48]:
np.quantile(dados, 0.5)

160.0

In [49]:
np.percentile(dados, 50)

160.0

In [50]:
np.percentile(dados, 5)

151.95

In [51]:
stats.scoreatpercentile(dados, 5), stats.scoreatpercentile(dados, 10), stats.scoreatpercentile(dados, 90)

(151.95000000000002, 152.89999999999998, 168.1)

In [52]:
dataset = pd.DataFrame(dados)
dataset.head()

0
0  150
1  151
2  152
3  152
4  153

In [53]:
dataset.quantile([0.5,0.10,0.90])

0
0.5  160.0
0.1  152.9
0.9  168.1

## Exercício

In [54]:
dataset = pd.read_csv('/content/drive/MyDrive/Estatística para Ciência de Dados e Machine Learning/Bases de dados/census.csv')

In [55]:
dataset.head()

age          workclass  final-weight   education  education-num  \
0   39          State-gov         77516   Bachelors             13   
1   50   Self-emp-not-inc         83311   Bachelors             13   
2   38            Private        215646     HS-grad              9   
3   53            Private        234721        11th              7   
4   28            Private        338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loos  hour-per-week  native-country  income  
0          2174             0             40   United-States   <=50K  
1             0             0             13   United-States   <=50K  
2             0             0             40   United-States   <=50K  
3             0             0             40   United-States   <=50K  
4             0             0             40            Cuba   <=50K

In [56]:
dataset['age'].mean()

38.58164675532078

In [57]:
stats.hmean(dataset['age'])

33.91874139089839

In [58]:
from scipy.stats.mstats import gmean
gmean(dataset['age'])

36.210879158177256

In [59]:
def quadratic_mean(dados):
  return math.sqrt(sum(n * n for n in dados) / len(dados))

In [60]:
quadratic_mean(dataset['age'])

40.9218664329987

In [61]:
dataset['age'].median()

37.0

In [62]:
statistics.mode(dataset['age'])

36

# Medidas de dispersão

## Amplitute total e diferença interquartil

In [63]:
dados

array([150, 151, 152, 152, 153, 154, 155, 155, 155, 155, 156, 156, 156,
       157, 158, 158, 160, 160, 160, 160, 160, 161, 161, 161, 161, 162,
       163, 163, 164, 164, 164, 165, 166, 167, 168, 168, 169, 170, 172,
       173])

In [64]:
dados.max() - dados.min()

23

In [65]:
q1 = np.quantile(dados, 0.25)
q3 = np.quantile(dados, 0.75)
q1, q3

(155.75, 164.0)

In [66]:
diferenca_interquartil = q3 - q1
diferenca_interquartil

8.25

In [67]:
inferior = q1 - (1.5 * diferenca_interquartil)
inferior

143.375

In [68]:
superior = q3 + (1.5 * diferenca_interquartil)
superior

176.375

## Variância e desvio padrão

In [69]:
dados_impar = np.array([150, 151, 152, 152,153, 154, 155, 155, 155])

### Cálculo manual

In [70]:
media = dados_impar.sum() / len(dados_impar)
media

153.0

In [71]:
desvio = abs(dados_impar - media)
desvio

array([3., 2., 1., 1., 0., 1., 2., 2., 2.])

In [72]:
desvio = desvio ** 2
desvio

array([9., 4., 1., 1., 0., 1., 4., 4., 4.])

In [73]:
soma_desvio = desvio.sum()
soma_desvio

28.0

In [74]:
v = soma_desvio / len(dados_impar)
v

3.111111111111111

In [75]:
dp = math.sqrt(v)
dp

1.7638342073763937

In [76]:
cv = (dp / media) * 100
cv

1.1528328152786886

### Bibliotecas

In [77]:
np.var(dados_impar)

3.111111111111111

In [78]:
np.var(dados)

33.984375

In [79]:
statistics.variance(dados)

34

In [80]:
from scipy import ndimage
ndimage.variance(dados)

33.984375

In [81]:
np.std(dados_impar)

1.7638342073763937

In [82]:
np.std(dados)

5.829611908180509

In [83]:
statistics.stdev(dados)

5.830951894845301

In [84]:
stats.tstd(dados, ddof=0)

5.829611908180509

In [85]:
stats.variation(dados_impar) * 100

1.1528328152786886

In [86]:
stats.variation(dados) * 100

3.634987939629312

## Testes com algoritmos de classificação

In [87]:
dataset = pd.read_csv('/content/drive/MyDrive/Estatística para Ciência de Dados e Machine Learning/Bases de dados/credit_data.csv')

In [88]:
dataset.dropna(inplace=True)
dataset.shape

(1997, 5)

In [89]:
dataset

i#clientid        income        age         loan  c#default
0              1  66155.925095  59.017015  8106.532131          0
1              2  34415.153966  48.117153  6564.745018          0
2              3  57317.170063  63.108049  8020.953296          0
3              4  42709.534201  45.751972  6103.642260          0
4              5  66952.688845  18.584336  8770.099235          1
...          ...           ...        ...          ...        ...
1995        1996  59221.044874  48.518179  1926.729397          0
1996        1997  69516.127573  23.162104  3503.176156          0
1997        1998  44311.449262  28.017167  5522.786693          1
1998        1999  43756.056605  63.971796  1622.722598          0
1999        2000  69436.579552  56.152617  7378.833599          0

[1997 rows x 5 columns]

In [90]:
X = dataset.iloc[:, 1:4].values
X

array([[6.61559251e+04, 5.90170151e+01, 8.10653213e+03],
       [3.44151540e+04, 4.81171531e+01, 6.56474502e+03],
       [5.73171701e+04, 6.31080495e+01, 8.02095330e+03],
       ...,
       [4.43114493e+04, 2.80171669e+01, 5.52278669e+03],
       [4.37560566e+04, 6.39717958e+01, 1.62272260e+03],
       [6.94365796e+04, 5.61526170e+01, 7.37883360e+03]])

In [91]:
y = dataset.iloc[:,4].values
y

array([0, 0, 0, ..., 1, 0, 0])

In [92]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [93]:
resultados_naive_bayes = []
resultados_logistica = []
resultados_forest = []
for i in range(30):
  X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size = 0.2, stratify=y, random_state = i)
  naive_bayes = GaussianNB()
  naive_bayes.fit(X_treinamento, y_treinamento)
  resultados_naive_bayes.append(accuracy_score(y_teste, naive_bayes.predict(X_teste)))

  logistica = LogisticRegression()
  logistica.fit(X_treinamento, y_treinamento)
  resultados_logistica.append(accuracy_score(y_teste, logistica.predict(X_teste)))

  random_forest = RandomForestClassifier()
  random_forest.fit(X_treinamento, y_treinamento)
  resultados_forest.append(accuracy_score(y_teste, random_forest.predict(X_teste)))


In [94]:
print(resultados_naive_bayes)

[0.925, 0.925, 0.9325, 0.925, 0.92, 0.905, 0.9175, 0.9175, 0.9125, 0.9325, 0.9225, 0.9125, 0.935, 0.9175, 0.925, 0.9175, 0.9275, 0.92, 0.9325, 0.92, 0.93, 0.905, 0.9175, 0.9325, 0.9425, 0.9375, 0.94, 0.92, 0.935, 0.925]


In [95]:
print(resultados_logistica)

[0.9325, 0.91, 0.9125, 0.9225, 0.9075, 0.89, 0.91, 0.9075, 0.8775, 0.915, 0.9175, 0.9, 0.925, 0.9175, 0.9025, 0.9125, 0.9525, 0.91, 0.9225, 0.9075, 0.925, 0.905, 0.9075, 0.945, 0.9225, 0.9275, 0.9225, 0.9175, 0.91, 0.9]


In [96]:
print(resultados_forest)

[0.975, 0.9875, 0.985, 0.995, 0.9725, 0.99, 0.985, 0.985, 0.9775, 0.99, 0.985, 0.9825, 0.9725, 0.9875, 0.98, 0.9775, 0.985, 0.9775, 0.99, 0.985, 0.98, 0.9725, 0.985, 0.9875, 0.9875, 0.995, 0.9925, 0.985, 0.9875, 0.9875]


In [98]:
resultados_naive_bayes = np.array(resultados_naive_bayes)
resultados_logistica = np.array(resultados_logistica)
resultados_forest = np.array(resultados_forest)

### Média

In [99]:
resultados_naive_bayes.mean(), resultados_logistica.mean(), resultados_forest.mean()

(0.92425, 0.9145, 0.9841666666666667)

### Moda

In [101]:
stats.mode(resultados_naive_bayes), stats.mode(resultados_logistica), stats.mode(resultados_forest)

(ModeResult(mode=array([0.9175]), count=array([5])),
 ModeResult(mode=array([0.9075]), count=array([4])),
 ModeResult(mode=array([0.985]), count=array([8])))

### Mediana

In [106]:
np.median(resultados_naive_bayes), np.median(resultados_logistica), np.median(resultados_forest)

(0.925, 0.9125, 0.985)

### Variância

In [108]:
np.set_printoptions(suppress=True)
np.var(resultados_naive_bayes), np.var(resultados_logistica), np.var(resultados_forest)

(8.756250000000001e-05, 0.00020933333333333337, 3.805555555555552e-05)

In [109]:
np.min([8.756250000000001e-05, 0.00020933333333333337, 3.805555555555552e-05])

3.805555555555552e-05

In [110]:
np.max([8.756250000000001e-05, 0.00020933333333333337, 3.805555555555552e-05])

0.00020933333333333337

In [111]:
resultados_forest

array([0.975 , 0.9875, 0.985 , 0.995 , 0.9725, 0.99  , 0.985 , 0.985 ,
       0.9775, 0.99  , 0.985 , 0.9825, 0.9725, 0.9875, 0.98  , 0.9775,
       0.985 , 0.9775, 0.99  , 0.985 , 0.98  , 0.9725, 0.985 , 0.9875,
       0.9875, 0.995 , 0.9925, 0.985 , 0.9875, 0.9875])

### Desvio Padrão

In [112]:
np.std(resultados_naive_bayes), np.std(resultados_logistica), np.std(resultados_forest)

(0.00935748363610645, 0.014468356276140472, 0.006168918507773913)

### Coeficiente de variação

In [113]:
stats.variation(resultados_naive_bayes) * 100, stats.variation(resultados_logistica) * 100, stats.variation(resultados_forest) * 100

(1.0124407504578252, 1.5821056616884057, 0.6268164444816846)

## Exercício : validação cruzada

In [115]:
from sklearn.model_selection import cross_val_score, KFold

In [116]:
resultados_naive_bayes_cv = []
resultados_logistica_cv = []
resultados_forest_cv = []
for i in range(30):
  kfold = KFold(n_splits = 10, shuffle = True, random_state=i)
  
  naive_bayes = GaussianNB()
  scores = cross_val_score(naive_bayes, X, y, cv = kfold)
  resultados_naive_bayes_cv.append(scores.mean())

  logistica = LogisticRegression()
  scores = cross_val_score(logistica, X, y, cv = kfold)
  resultados_logistica_cv.append(scores.mean())

  random_forest = RandomForestClassifier()
  scores = cross_val_score(random_forest, X, y, cv = kfold)
  resultados_forest_cv.append(scores.mean())

In [117]:
scores, 10 * 30

(array([0.985     , 0.98      , 0.99      , 0.99      , 0.975     ,
        0.985     , 0.99      , 0.9798995 , 0.98492462, 1.        ]), 300)

In [119]:
scores.mean()

0.9859824120603016

In [120]:
print(resultados_naive_bayes_cv)

[0.9248618090452261, 0.9249170854271356, 0.9248894472361808, 0.9228819095477387, 0.9248718592964824, 0.9253894472361809, 0.9243844221105528, 0.9248894472361808, 0.9248718592964824, 0.9238894472361808, 0.9253844221105527, 0.9244020100502512, 0.9253743718592965, 0.924394472361809, 0.9253869346733667, 0.9248819095477387, 0.9258844221105527, 0.924894472361809, 0.9238819095477387, 0.9258844221105529, 0.9258944723618091, 0.9253894472361811, 0.92436432160804, 0.9263844221105527, 0.9228944723618092, 0.9253894472361809, 0.9248869346733668, 0.9253919597989949, 0.9253819095477386, 0.9258844221105527]


In [121]:
print(resultados_logistica_cv)

[0.9113718592964826, 0.9103668341708543, 0.918359296482412, 0.9158768844221106, 0.9133417085427136, 0.9108718592964824, 0.9188366834170856, 0.9188969849246231, 0.913356783919598, 0.9148693467336683, 0.9098718592964824, 0.9183542713567838, 0.9183793969849248, 0.9213618090452261, 0.9098643216080402, 0.914356783919598, 0.9103693467336684, 0.915856783919598, 0.9128542713567839, 0.9123668341708543, 0.9208944723618091, 0.9108668341708542, 0.9103467336683417, 0.9133768844221105, 0.9098592964824121, 0.9148768844221105, 0.910859296482412, 0.9113768844221104, 0.9113668341708543, 0.9098442211055277]


In [122]:
print(resultados_forest_cv)

[0.9849723618090452, 0.9854849246231157, 0.9859824120603016, 0.9859648241206032, 0.9889874371859296, 0.9859824120603016, 0.9879748743718594, 0.9859849246231155, 0.9859773869346734, 0.9859824120603016, 0.9884824120603015, 0.9879748743718594, 0.9884773869346735, 0.9879798994974875, 0.9894874371859297, 0.9889849246231156, 0.9864849246231155, 0.9884723618090453, 0.9869849246231157, 0.9824748743718594, 0.9844723618090452, 0.9864748743718593, 0.9854798994974875, 0.9884798994974874, 0.9869773869346734, 0.9859899497487437, 0.9854748743718593, 0.9874798994974874, 0.9899874371859296, 0.9859824120603016]


In [123]:
stats.variation(resultados_naive_bayes) * 100, stats.variation(resultados_logistica) * 100, stats.variation(resultados_forest) * 100

(1.0124407504578252, 1.5821056616884057, 0.6268164444816846)

In [124]:
stats.variation(resultados_naive_bayes_cv) * 100, stats.variation(resultados_logistica_cv) * 100, stats.variation(resultados_forest_cv) * 100

(0.08641071566366061, 0.38801026116292653, 0.16653603491066538)

## Seleção de atributos utilizando variância

In [125]:
np.random.rand(50)

array([0.26779785, 0.56678903, 0.98310253, 0.83760622, 0.04254494,
       0.85776625, 0.81474826, 0.53553645, 0.31422942, 0.19311856,
       0.9782443 , 0.63418129, 0.27139171, 0.95705258, 0.36406836,
       0.76440608, 0.71902961, 0.10971837, 0.65175368, 0.2177574 ,
       0.54108213, 0.38760851, 0.04363479, 0.15985941, 0.58146105,
       0.00563879, 0.98402711, 0.61210766, 0.46249519, 0.87343466,
       0.25096038, 0.77072395, 0.00297784, 0.40751884, 0.57159855,
       0.17767805, 0.1346287 , 0.05000127, 0.68481864, 0.11082346,
       0.82840092, 0.39439254, 0.01127547, 0.68296085, 0.93766517,
       0.38958416, 0.78641885, 0.71634659, 0.52239157, 0.11762873])

In [126]:
base_selecao = {'a': np.random.rand(20),
                'b': np.array([0.5] * 20),
                'classe' : np.random.randint(0,2,size=20)}

In [127]:
base_selecao

{'a': array([0.08005274, 0.01275191, 0.70274356, 0.65485245, 0.1260483 ,
        0.22315558, 0.60003922, 0.69363392, 0.63443478, 0.71624305,
        0.47163568, 0.59209693, 0.69569536, 0.24480012, 0.02614946,
        0.74631701, 0.22320387, 0.47477627, 0.39433686, 0.22971614]),
 'b': array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5,
        0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]),
 'classe': array([0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0])}

In [129]:
dataset = pd.DataFrame(base_selecao)
dataset.head()

a    b  classe
0  0.080053  0.5       0
1  0.012752  0.5       0
2  0.702744  0.5       1
3  0.654852  0.5       1
4  0.126048  0.5       1

In [130]:
dataset.describe()

a     b     classe
count  20.000000  20.0  20.000000
mean    0.427134   0.5   0.550000
std     0.257607   0.0   0.510418
min     0.012752   0.5   0.000000
25%     0.223192   0.5   0.000000
50%     0.473206   0.5   1.000000
75%     0.664548   0.5   1.000000
max     0.746317   0.5   1.000000

In [131]:
np.var(dataset['a']), np.var(dataset['b'])

(0.06304336367275065, 0.0)

In [132]:
X = dataset.iloc[:, 0:2].values
y = dataset.iloc[:,2].values

In [133]:
from sklearn.feature_selection import VarianceThreshold

In [135]:
selecao = VarianceThreshold(threshold=0.05)
X_novo = selecao.fit_transform(X)

In [136]:
X_novo

array([[0.08005274],
       [0.01275191],
       [0.70274356],
       [0.65485245],
       [0.1260483 ],
       [0.22315558],
       [0.60003922],
       [0.69363392],
       [0.63443478],
       [0.71624305],
       [0.47163568],
       [0.59209693],
       [0.69569536],
       [0.24480012],
       [0.02614946],
       [0.74631701],
       [0.22320387],
       [0.47477627],
       [0.39433686],
       [0.22971614]])

In [137]:
X_novo.shape

(20, 1)

In [138]:
selecao.variances_

array([0.06304336, 0.        ])

In [139]:
indices = np.where(selecao.variances_ > 0.05)
indices

(array([0]),)